nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: 192.168.167.5

  # Wazuh manager nodes
  server:
    - name: wazuh-1
      ip: 192.168.167.5

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: 192.168.167.5
