---
- hosts: Honeypot_Hosts
  collections:
    - community.docker
  become: true
  vars:
    docker_image_name: honeypot
    docker_image_tag: conpot
    dockerfile_path: ~/
  tasks:
    - name: Install prerequisites for Docker repository
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes
    - name: install docker and its dependencies
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
     - name: Install docker-compose
       remote_user: student
       get_url: 
         url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
    - name: start and enable docker daemon
      service:
        name: docker
        state: started
        enabled: yes          
    - name: Clone conpot repository
      git: 
        repo: https://github.com/chandieka/HoneyMonX.git
        dest: /home/
        clone: yes
        update: yes
    - name: Deploy Docker compose
      community.docker.docker_compose:
        project_src: /honeypot/conpot
        files:
        - docker-compose.yml
