---
- name: Deploy the Wazuh monitoring dashboard
  ansible.builtin.import_playbook: honeymonx-automation-monitoring.yml

- name: Deploy the Conpot docker image
  ansible.builtin.import_playbook: honeymonx-automation-conpot.yml

- name: Deploy the Wazuh agents
  ansible.builtin.import_playbook: honeymonx-automation-agents.yml

- name: Overwrite the custom rules for the Manager and Agents
  ansible.builtin.import_playbook: honeymonx-automation-custom-rules.yml
