---
- hosts: Honeypot_Hosts
  collections:
    - community.docker
  become: true
  vars:
    docker_image_name: honeypot
    docker_image_tag: conpot

#Installation of Docker dependencies
  tasks:
    - name: Install prerequisites for Docker repository
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes
    - name: install docker and its dependencies
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present
    - name: start and enable docker daemon
      service:
        name: docker
        state: started
        enabled: yes          

#Clone the HoneyMonX Git Repo and launch 
    - name: Clone conpot repository
      git: 
        repo: https://github.com/chandieka/HoneyMonX.git
        dest: "~/HoneyMonX"
        clone: yes
        update: yes
    - name: Deploy Docker compose
      community.docker.docker_compose:
        project_src: ~/HoneyMonX/honeypot/conpot
        files:
        - docker-compose.yml
        
# Wazuh - Certificates generation
  - hosts: localhost
    roles:
      - role: ../roles/wazuh/wazuh-indexer
        perform_installation: false
    become: no
    vars:
      indexer_node_master: true
      instances:
        node1:
          name: node-1
          ip: 127.0.0.1
          role: indexer
    tags:
      - generate-certs
      
# Wazuh Dashboard installation
  - hosts: localhost
    become: yes
    become_user: root
    roles:
      - role: ../roles/wazuh/wazuh-indexer
      - role: ../roles/wazuh/ansible-wazuh-manager
      - role: ../roles/wazuh/ansible-filebeat-oss
      - role: ../roles/wazuh/wazuh-dashboard
    vars:
      single_node: true
      minimum_master_nodes: 1
      indexer_node_master: true
      indexer_network_host: 127.0.0.1
      filebeat_node_name: node-1
      filebeat_output_indexer_hosts:
      - 127.0.0.1
      instances:
        node1:
          name: node-1
          ip: 127.0.0.1
          role: indexer
      ansible_shell_allow_world_readable_temp: true
      
   - hosts: Honeypot_Hosts
     become: yes
     become_user: root
     roles:
       - ../roles/wazuh/ansible-wazuh-agent
     vars:
       wazuh_managers:
         - address: 192.168.167.5
           port: 1514
           protocol: tcp
           api_port: 55000
           api_proto: 'http'
           api_user: ansible
           max_retries: 5
           retry_interval: 5
