---
#Copy custom conpot_rules, suricata_rules, export.ndjson and shared agent config to Wazuh Manager
- hosts: Honeypot_Master_Dashboard
  tasks:
    - name: Copy agents.conf to the wazuh manager
      ansible.builtin.copy:
        src: ../config/wazuh/wazuh-agent/conpot/agent.conf
        dest: /var/ossec/etc/shared/default
        owner: root
      become: yes
    
    - name: Copy conpot_rules to the wazuh manager
      ansible.builtin.copy:
        src: ../config/wazuh/wazuh-manager/conpot_rules.xml
        dest: /var/ossec/etc/rules/
        owner: root
      become: yes
      
    - name: Copy overwrite_suricata_rules to wazuh the manager
      ansible.builtin.copy:
        src: ../config/wazuh/wazuh-manager/overwrite_suricata_rules.xml
        dest: /var/ossec/etc/rules/
        owner: root
      become: yes     
      
    - name: Copy export.ndJson file to the wazuh manager
      ansible.builtin.copy:
        src: ../config/wazuh/wazuh-manager/export.ndjson
        dest: /home/student/Documents/
        owner: root
      become: yes
      
#TODO: Curl export.ndjson to the Wazuh manager API and restart the indexer     
#      URL - https://localhost/app/management/opensearch-dashboard/objects

    - name: restart Wazuh Manager
      ansible.builtin.command:
        cmd: systemctl restart wazuh-indexer.service
      become: yes     
