---
- hosts: Honeypot_Master_Dashboard
  roles:
    - role: ../roles/wazuh/wazuh-indexer
      perform_installation: false
  become: no
  vars:
    indexer_node_master: true
    instances:
      node1:
        name: node-1
        ip: 127.0.0.1
        role: indexer
  tags:
    - generate-certs
      
# Wazuh Indexer, Manager & Dashboard installation
- name: "Wazuh Indexer and Manager"
  hosts: Honeypot_Master_Dashboard
  become: yes
  become_user: root
  roles:
    - role: ../roles/wazuh/wazuh-indexer
    - role: ../roles/wazuh/ansible-wazuh-manager
    - role: ../roles/wazuh/ansible-filebeat-oss
    - role: ../roles/wazuh/wazuh-dashboard
  vars:
    single_node: true
    minimum_master_nodes: 1
    indexer_node_master: true
    indexer_network_host: 127.0.0.1
    filebeat_node_name: node-1
    filebeat_output_indexer_hosts:
    - 127.0.0.1
    instances:
      node1:
        name: node-1
        ip: 127.0.0.1
        role: indexer
    ansible_shell_allow_world_readable_temp: true
